name: vibelift
description: A visually appealing, offline-first fitness tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # HTTP Client
  http: ^1.2.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Animations
  lottie: ^3.0.0
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # UI Enhancements
  intl: ^0.19.0
  shimmer: ^3.0.0
  
  # Utils
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/lottie/
    - assets/images/
  
  # Uncomment after downloading Poppins font files
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

